### ISSUE TITLE
Stratum doesn't establish connection to XZC

### ISSUE THREAD

**Issue by gr33k** [MintPond/mtp-stratum-mining-protocol#1]
Hi There! 

I'm trying to get this working with yiimp and ZCoin and I have the stratum compiled and starting just fine...however I don't see it actually establishing a connection with the local daemon (running on localhost):

18:32:24: 2019-08-13 starting stratum for mtp on mypool.example.com:5432
18:32:24: connecting to coind XZC

I have other coins working just fine but are supported algo's of course.

When miner connects it says stratum_subscribe timed out. So it does establish a connection to the stratum service but doesn't get any work from what I'm seeing. Any ideas perhaps?

**Comment by JCThePants** [comment]
This repo is just protocol documentation. You might try the yiimp repo for support.

**Comment by goodthebest** [comment]
@gr33k did you make mtp work?
